version: '2'
services:
  ssh-honeypot:
    image: 'local/ssh-honeypot:latest'
    build: .
    ports:
      - '22:2022'
    volumes:
      - /var/log/serverlogs/ssh-log:/home/honeycomb/log
      - /var/log/serverlogs/ssh-rsa:/home/honeycomb/rsa     
    networks:
      default: 
    restart: unless-stopped

volumes:
  log:
    driver: local
  rsa:
    driver: local

networks:
  default:
